### PR TITLE
Updating all package dependencies to include Bunyan 1.3.4

### PR DESCRIPTION
**Pull request by nycjoker**
Updating all package dependencies. All mocha tests pass successfully.

### CODE REVIEW

**Comment by ericelliott** [comment]
Merged, updated, and pushed as v1.0.0.

**Comment by nycjoker** [comment]
Don't see version 1.0.0 increment.

**Comment by ericelliott** [comment]
Not sure why you don't see it. [It's here](https://github.com/ericelliott/bunyan-request-logger/releases/tag/v1.0.0).

```
$ npm info
{ name: 'bunyan-request-logger',
  description: 'Automated request logging connect middleware for Express. Powered by Bunyan.',
  'dist-tags': { latest: '1.0.0' },
  versions: 
   [ '0.1.1',
     '0.2.0',
     '0.2.1',
     '0.2.2',
     '0.2.3',
     '0.2.5',
     '0.2.6',
     '1.0.0' ],
#...
```

**Comment by nycjoker** [comment]
Gotcha. I'm looking at the version in package.json on github.

**Comment by ericelliott** [comment]
Oh that's crazy. It should have updated that.

**Pull request merged**
