### PR TITLE
add tests on log.route

### PR DESCRIPTION
**Pull request by amelon**

### CODE REVIEW

**Comment by ericelliott** [comment]
Thanks. Sorry it's taking me so long to get around to this!

**Comment by ericelliott** [comment]
I'm seeing the following test failures on this branch:

```
  22 passing (258ms)
  3 failing

  1) bunyan-request-logger log.route logging should log the request params:
     Uncaught TypeError: Cannot read property 'msg' of undefined
      at Test.<anonymous> (/Users/eric/Dropbox/dev/bunyan-request-logger/test/log.route.js:73:37)
      at Test.assert (/Users/eric/Dropbox/dev/bunyan-request-logger/node_modules/supertest/lib/test.js:221:6)
      at Server.assert (/Users/eric/Dropbox/dev/bunyan-request-logger/node_modules/supertest/lib/test.js:132:12)
      at Server.g (events.js:260:16)
      at emitNone (events.js:67:13)
      at Server.emit (events.js:166:7)
      at emitCloseNT (net.js:1521:8)
      at doNTCallback1 (node.js:430:9)
      at process._tickCallback (node.js:352:17)

  2) bunyan-request-logger log.route response should not be cached:
     Uncaught TypeError: Cannot read property 'should' of undefined
      at Test.<anonymous> (/Users/eric/Dropbox/dev/bunyan-request-logger/test/log.route.js:86:39)
      at Test.assert (/Users/eric/Dropbox/dev/bunyan-request-logger/node_modules/supertest/lib/test.js:221:6)
      at Server.assert (/Users/eric/Dropbox/dev/bunyan-request-logger/node_modules/supertest/lib/test.js:132:12)
      at Server.g (events.js:260:16)
      at emitNone (events.js:67:13)
      at Server.emit (events.js:166:7)
      at emitCloseNT (net.js:1521:8)
      at doNTCallback1 (node.js:430:9)
      at process._tickCallback (node.js:352:17)

  3) bunyan-request-logger log.route response should be a gif image:

      Uncaught AssertionError: expected 'text/html; charset=utf-8' to be 'image/gif'
      + expected - actual

      +image/gif
      -text/html; charset=utf-8
      
      at Assertion.fail (/Users/eric/Dropbox/dev/bunyan-request-logger/node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value (/Users/eric/Dropbox/dev/bunyan-request-logger/node_modules/should/lib/assertion.js:65:17)
      at Test.<anonymous> (/Users/eric/Dropbox/dev/bunyan-request-logger/test/log.route.js:97:49)
      at Test.assert (/Users/eric/Dropbox/dev/bunyan-request-logger/node_modules/supertest/lib/test.js:221:6)
      at Server.assert (/Users/eric/Dropbox/dev/bunyan-request-logger/node_modules/supertest/lib/test.js:132:12)
      at Server.g (events.js:260:16)
      at emitNone (events.js:67:13)
      at Server.emit (events.js:166:7)
      at emitCloseNT (net.js:1521:8)
      at doNTCallback1 (node.js:430:9)
      at process._tickCallback (node.js:352:17)



npm ERR! Test failed.  See above for more details.
```

I have verified that all tests are passing on Master.

**Comment by amelon** [comment]
very strange, I ran tests on my laptop and everything was ok.
Let me check.

**Comment by viggeh** [comment]
@amelon Please update your branch so that you have the changes from #19 . Then we can see if tests are passing. You will probably need to enable your repo in travis as well.

**Comment by ericelliott** [comment]
```sh
 bunyan-request-logger log.gif
    logging
      ✓ should log the request id in the response at the info level 
      ✓ should log the request at the info level 
      ✓ should log the request id at the info level 
      ✓ should log the request params 
    response
      ✓ should not be cached 
      1) should be a gif image

  bunyan-request-logger serializers
    res serializer
      ✓ should log the correct properties when logging the response 
      ✓ should log the correct properties for the res object when logging the response 
    res serializer
      ✓ should log the correct properties when logging the response 
      ✓ should log the correct properties for the req object when logging the response 
    err serializer
      ✓ should log the correct properties when logging the response 
      ✓ should log the correct properties for the err object when logging the response 
      ✓ should not log the stack on 4xx errors 


  24 passing (217ms)
  1 failing

  1) bunyan-request-logger log.gif response should be a gif image:
     Uncaught TypeError: Cannot read property 'should' of undefined
```

**Comment by amelon** [comment]
something unclear for me.
Find below, test results on my laptop:

````
 bunyan-request-logger log.gif
    logging
      √ should log the request id in the response at the info level
      √ should log the request at the info level
      √ should log the request id at the info level
      √ should log the request params
    response
      √ should not be cached
      √ should be a gif image
````

How is it possible?
Could you tell me which header is not present (content-type or content-length)?

**Comment by viggeh** [comment]
@amelon Note that the test is failing when running in NodeJS 0.12.x. It seems that the ```content-length``` header is not set because the ```transfer-encoding``` header is set as ```chunked```. Please update your test and remove the ```res.headers['content-length'].should.be.equal('35');``` check as it doe  not apply.

**Comment by amelon** [comment]
@viggeh thanks for your help.
I fetched/merged original repo, setup travis and removed content-length check.
Everything is ok now on travis.

**Comment by ericelliott** [comment]
Thanks! =)

**Pull request merged**
